### ISSUE TITLE
Post suggestion to Discord Channel when suggestion is created via discord command

### ISSUE THREAD

**Issue by MJonah** [supercrafter100/Nameless-Suggestions-Discord-Bot#11]
It would be nice when a suggestion is created via the /suggest command, the webhook posts it in the suggestions channel, and does not only create in Nameless.

**Comment by supercrafter100** [comment]
It should do this if you've setup the webhook correctly, any suggestion created on your website should (if you've set the webhook on your site up correctly) send a message to your suggestion channel

**Comment by MJonah** [comment]
If I create a suggestion on the website, it gets posted inside Discord. But it doesn't work when I create it via the /suggest command for some reason

**Comment by supercrafter100** [comment]
Did the suggestion get created on the website?

**Comment by MJonah** [comment]
> Did the suggestion get created on the website?

Yes.

**Comment by supercrafter100** [comment]
Mind using the command (/suggest) again? I'll check for errors

**Comment by MJonah** [comment]
That's one thing I didn't test, i'll try it with the public bot now one sec..

**Comment by supercrafter100** [comment]
Looks like it worked this time?

**Comment by MJonah** [comment]
Ok, it's not working on the selfhosted bot...

**Comment by supercrafter100** [comment]
I got the request on the public bot at least

**Comment by supercrafter100** [comment]
ah right. What's your tag?

**Comment by supercrafter100** [comment]
Resolved in discord
