### ISSUE TITLE
bot fails to run on linux

### ISSUE THREAD

**Issue by xsmeths** [supercrafter100/Nameless-Suggestions-Discord-Bot#12]
the public bot went down so I figured I'd try self-host it, only to find out it doesn't run either that way, what am I doing wrong (if anything) ?

Error: Cannot find module 'node:events'

along with a bunch of refs to discord-api so I'm assuming either It's based on a now completely unusable part of the discord api or I did something wrong

**Comment by supercrafter100** [comment]
Public bot looks fine to me? Been running for the past month without issues.

**Comment by supercrafter100** [comment]
Anyways did you install the dependencies?

**Comment by supercrafter100** [comment]
I don’t know if the latest code on GitHub will currently work though. Ive pushed changes to it that are in preparation for the next namelessmc release.

**Comment by xsmeths** [comment]
![Screenshot_186](https://user-images.githubusercontent.com/6798793/228061520-26532f47-3381-44bc-a797-88a33be1553b.png)
I'm confuised

**Comment by xsmeths** [comment]
I followed the readme's instructions exactly

**Comment by xsmeths** [comment]
I sent you a dm, I hope that's okay
